# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.12
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info >= (2, 7, 0):
    def swig_import_helper():
        import importlib
        pkg = __name__.rpartition('.')[0]
        mname = '.'.join((pkg, '_RTLSClient')).lstrip('.')
        try:
            return importlib.import_module(mname)
        except ImportError:
            return importlib.import_module('_RTLSClient')
    _RTLSClient = swig_import_helper()
    del swig_import_helper
elif _swig_python_version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_RTLSClient', [dirname(__file__)])
        except ImportError:
            import _RTLSClient
            return _RTLSClient
        try:
            _mod = imp.load_module('_RTLSClient', fp, pathname, description)
        finally:
            if fp is not None:
                fp.close()
        return _mod
    _RTLSClient = swig_import_helper()
    del swig_import_helper
else:
    import _RTLSClient
del _swig_python_version_info

try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr(self, class_type, name):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except __builtin__.Exception:
    class _object:
        pass
    _newclass = 0

class vec3d(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, vec3d, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, vec3d, name)
    __repr__ = _swig_repr
    __swig_setmethods__["x"] = _RTLSClient.vec3d_x_set
    __swig_getmethods__["x"] = _RTLSClient.vec3d_x_get
    if _newclass:
        x = _swig_property(_RTLSClient.vec3d_x_get, _RTLSClient.vec3d_x_set)
    __swig_setmethods__["y"] = _RTLSClient.vec3d_y_set
    __swig_getmethods__["y"] = _RTLSClient.vec3d_y_get
    if _newclass:
        y = _swig_property(_RTLSClient.vec3d_y_get, _RTLSClient.vec3d_y_set)
    __swig_setmethods__["z"] = _RTLSClient.vec3d_z_set
    __swig_getmethods__["z"] = _RTLSClient.vec3d_z_get
    if _newclass:
        z = _swig_property(_RTLSClient.vec3d_z_get, _RTLSClient.vec3d_z_set)

    def __init__(self):
        this = _RTLSClient.new_vec3d()
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _RTLSClient.delete_vec3d
    __del__ = lambda self: None
vec3d_swigregister = _RTLSClient.vec3d_swigregister
vec3d_swigregister(vec3d)

class RTLSClient(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, RTLSClient, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, RTLSClient, name)
    __repr__ = _swig_repr

    def __init__(self, anchor_0, anchor_1, anchor_2, anchor_3):
        this = _RTLSClient.new_RTLSClient(anchor_0, anchor_1, anchor_2, anchor_3)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _RTLSClient.delete_RTLSClient
    __del__ = lambda self: None

    def calculateTagLocation(self, report, count, ranges):
        return _RTLSClient.RTLSClient_calculateTagLocation(self, report, count, ranges)

    def trilaterateTag(self, range_0, range_1, range_2, range_3, count):
        return _RTLSClient.RTLSClient_trilaterateTag(self, range_0, range_1, range_2, range_3, count)
RTLSClient_swigregister = _RTLSClient.RTLSClient_swigregister
RTLSClient_swigregister(RTLSClient)

# This file is compatible with both classic and new-style classes.


